In [7]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# 1. Load the Breast Cancer dataset
data = load_breast_cancer()

# 2. Separate the features and target variable
X = data.data  
y = data.target # Target classes: 0 (Malignant), 1 (Benign)

# 4. Divide the dataset into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_test_size=0.2, random_state=42, stratify=y
)

# 3. Perform appropriate feature scaling (Crucial for gradient convergence)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 5. Construct an MLP classifier
# Architecture: 30 Input -> 64 Hidden -> 32 Hidden -> 1 Output (Binary)
mlp = MLPClassifier(
    hidden_layer_sizes=(64, 32),
    activation='relu',       # Activation function for hidden layers
    solver='adam',           # Optimization algorithm
    max_iter=300,            # Maximum training epochs
    random_state=42
)

# 6. Train the MLP using the training data
mlp.fit(X_train_scaled, y_train)

# 7. Predict the classes of the test data
y_pred = mlp.predict(X_test_scaled)

# 8. Evaluate the trained model & 9. Display the classification results
print("=== Part A: Scikit-Learn MLP Classifier Results ===")
print(f"Test Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%\n")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=data.target_names))


TypeError: got an unexpected keyword argument 'test_test_size'

In [ ]:
# Multilayer Perceptron for Breast Cancer Classification
# Aim
# To implement a Multilayer Perceptron (MLP) classifier for breast cancer classification
# using:
# 1. a machine-learning library, and
# 2. a from-scratch implementation using NumPy, forward propagation, and backpropagation.
# Dataset
# Use the Breast Cancer Wisconsin Diagnostic Dataset available through sklearn.datasets.
# The dataset contains:
# • Number of samples: 569
# • Number of features: 30
# • Number of classes: 2
# • Target classes: Malignant and Benign
# Part A: MLP Using a Machine-Learning Library
# Task
# Develop an MLP classifier to predict whether a breast tumor is malignant or benign.
# Students must perform the following steps:
# 1. Load the Breast Cancer dataset.
# 2. Separate the features and target variable.
# 3. Perform appropriate feature scaling.
# 4. Divide the dataset into training and testing sets.
# 5. Construct an MLP classifier containing:
# • Input layer
# • One or more hidden layers
# • Output layer
# 6. Train the MLP using the training data.
# 7. Predict the classes of the test data.
# 8. Evaluate the trained model.
# 9. Display the classification results.
# 1
# Experimental Study
# Students must investigate the effect of changing the following parameters:
# No. Parameter to Investigate
# 1 Number of hidden layers
# 2 Number of neurons in each hidden layer
# 3 Learning rate
# 4 Number of training iterations/epochs
# 5 Activation function
# Table 1: MLP parameters for experimental study
# Students should change one parameter at a time while keeping the other parameters
# fixed and observe the effect on model performance.
# Questions
# 1. What happens to the model when the number of neurons in the hidden layer is
# increased?
# 2. What happens when the learning rate is very small?
# 3. What happens when the learning rate is very large?
# 4. Compare an MLP with one hidden layer and an MLP with two hidden layers.
# 5. Why is a nonlinear activation function required in the hidden layers?
# 6. What happens if all the layers use a linear activation function?
# 7. Why can increasing the number of hidden neurons sometimes lead to overfitting?
# Part B: MLP From Scratch
# Task
# Implement an MLP from scratch for the same Breast Cancer Wisconsin Diagnostic
# Dataset.
# The implementation must not use an existing MLP or neural-network implementation
# from a machine-learning library.
# Students may use NumPy for matrix operations and numerical computations.
# The implementation must include the following components:
# 1. Weight initialization
# 2. Bias initialization
# 3. Forward propagation
# 4. Activation function
# 5. Loss/error calculation
# 6. Backpropagation
# 7. Weight update
# 8. Bias update
# 9. Iterative training
# 10. Prediction

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [10]:
# Load dataset
data = load_breast_cancer()

X = data.data
y = data.target

print("Number of samples:", X.shape[0])
print("Number of features:", X.shape[1])
print("Classes:", data.target_names)

Number of samples: 569
Number of features: 30
Classes: ['malignant' 'benign']


In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 455
Testing samples: 114


In [12]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
mlp = MLPClassifier(
    hidden_layer_sizes=(10,),
    activation='relu',
    learning_rate_init=0.001,
    max_iter=500,
    random_state=42
)

mlp.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(10,), max_iter=500, random_state=42)

In [14]:
y_pred = mlp.predict(X_test)

print("Predicted classes:")
print(y_pred)


Predicted classes:
[0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1
 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 0 1 1 1 1 1 1 0
 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 0 1
 0 1 1]


In [15]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=data.target_names
))


Accuracy: 0.9649122807017544

Confusion Matrix:
[[41  1]
 [ 3 69]]

Classification Report:
              precision    recall  f1-score   support

   malignant       0.93      0.98      0.95        42
      benign       0.99      0.96      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.97      0.96       114
weighted avg       0.97      0.96      0.97       114



In [16]:
models = {
    "1 Hidden Layer": (10,),
    "2 Hidden Layers": (10, 10),
    "3 Hidden Layers": (10, 10, 10)
}

for name, layers in models.items():
    model = MLPClassifier(
        hidden_layer_sizes=layers,
        activation='relu',
        learning_rate_init=0.001,
        max_iter=500,
        random_state=42
    )
    
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    
    print(name, "Accuracy:", accuracy_score(y_test, pred))


1 Hidden Layer Accuracy: 0.9649122807017544
2 Hidden Layers Accuracy: 0.9473684210526315
3 Hidden Layers Accuracy: 0.956140350877193


In [17]:
neurons = [5, 10, 20, 50]

for n in neurons:
    model = MLPClassifier(
        hidden_layer_sizes=(n,),
        activation='relu',
        learning_rate_init=0.001,
        max_iter=500,
        random_state=42
    )
    
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    
    print("Neurons:", n, "Accuracy:", accuracy_score(y_test, pred))


Neurons: 5 Accuracy: 0.9649122807017544
Neurons: 10 Accuracy: 0.9649122807017544
Neurons: 20 Accuracy: 0.956140350877193
Neurons: 50 Accuracy: 0.956140350877193


In [18]:
learning_rates = [0.0001, 0.001, 0.01, 0.1]

for lr in learning_rates:
    model = MLPClassifier(
        hidden_layer_sizes=(10,),
        activation='relu',
        learning_rate_init=lr,
        max_iter=500,
        random_state=42
    )
    
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    
    print("Learning Rate:", lr,
          "Accuracy:", accuracy_score(y_test, pred))


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


Learning Rate: 0.0001 Accuracy: 0.9473684210526315
Learning Rate: 0.001 Accuracy: 0.9649122807017544
Learning Rate: 0.01 Accuracy: 0.956140350877193
Learning Rate: 0.1 Accuracy: 0.9736842105263158


In [19]:
iterations = [100, 300, 500, 1000]

for it in iterations:
    model = MLPClassifier(
        hidden_layer_sizes=(10,),
        activation='relu',
        learning_rate_init=0.001,
        max_iter=it,
        random_state=42
    )
    
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    
    print("Iterations:", it,
          "Accuracy:", accuracy_score(y_test, pred))


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


Iterations: 100 Accuracy: 0.956140350877193
Iterations: 300 Accuracy: 0.9649122807017544
Iterations: 500 Accuracy: 0.9649122807017544
Iterations: 1000 Accuracy: 0.9649122807017544


In [20]:
activations = ['relu', 'tanh', 'logistic']

for act in activations:
    model = MLPClassifier(
        hidden_layer_sizes=(10,),
        activation=act,
        learning_rate_init=0.001,
        max_iter=500,
        random_state=42
    )
    
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    
    print("Activation:", act,
          "Accuracy:", accuracy_score(y_test, pred))


Activation: relu Accuracy: 0.9649122807017544
Activation: tanh Accuracy: 0.9649122807017544
Activation: logistic Accuracy: 0.956140350877193


In [21]:
#part B

In [27]:
# Load dataset again
data = load_breast_cancer()

X = data.data
y = data.target.reshape(-1, 1)

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Scale features
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train.shape)
print(y_train.shape)


(455, 30)
(455, 1)


In [28]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)


In [29]:
np.random.seed(42)

input_neurons = 30
hidden_neurons = 10
output_neurons = 1

# Weights
W1 = np.random.randn(input_neurons, hidden_neurons) * 0.01
W2 = np.random.randn(hidden_neurons, output_neurons) * 0.01

# Biases
b1 = np.zeros((1, hidden_neurons))
b2 = np.zeros((1, output_neurons))


In [30]:
def forward(X):
    # Hidden layer
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)

    # Output layer
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    return z1, a1, z2, a2


In [31]:
def loss_function(y, y_pred):
    epsilon = 1e-8
    
    loss = -np.mean(
        y * np.log(y_pred + epsilon) +
        (1 - y) * np.log(1 - y_pred + epsilon)
    )
    
    return loss


In [32]:
learning_rate = 0.1
epochs = 1000

for epoch in range(epochs):

    # -----------------
    # Forward propagation
    # -----------------
    z1, a1, z2, a2 = forward(X_train)

    # -----------------
    # Calculate loss
    # -----------------
    loss = loss_function(y_train, a2)

    # -----------------
    # Backpropagation
    # -----------------

    # Output layer error
    dz2 = a2 - y_train

    dW2 = np.dot(a1.T, dz2) / len(X_train)
    db2 = np.sum(dz2, axis=0, keepdims=True) / len(X_train)

    # Hidden layer error
    dz1 = np.dot(dz2, W2.T) * sigmoid_derivative(z1)

    dW1 = np.dot(X_train.T, dz1) / len(X_train)
    db1 = np.sum(dz1, axis=0, keepdims=True) / len(X_train)

    # -----------------
    # Update weights
    # -----------------

    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2

    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1

    # Print loss
    if epoch % 100 == 0:
        print("Epoch:", epoch, "Loss:", loss)


Epoch: 0 Loss: 0.6924690828722327
Epoch: 100 Loss: 0.4915220926186642
Epoch: 200 Loss: 0.2897868820568879
Epoch: 300 Loss: 0.19763686676286488
Epoch: 400 Loss: 0.1513487920612129
Epoch: 500 Loss: 0.12496806642399279
Epoch: 600 Loss: 0.10835632499430209
Epoch: 700 Loss: 0.0971222875497294
Epoch: 800 Loss: 0.089098178982676
Epoch: 900 Loss: 0.08310815757989658


In [33]:
_, _, _, y_probability = forward(X_test)

# Convert probability to class
y_pred = (y_probability >= 0.5).astype(int)

print("Predictions:")
print(y_pred[:10].flatten())


Predictions:
[0 1 0 1 0 1 1 0 0 0]


In [34]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=data.target_names
))


Accuracy: 0.9824561403508771

Confusion Matrix:
[[41  1]
 [ 1 71]]

Classification Report:
              precision    recall  f1-score   support

   malignant       0.98      0.98      0.98        42
      benign       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114



In [35]:
result = pd.DataFrame({
    "Actual": y_test.flatten(),
    "Predicted": y_pred.flatten()
})

print(result.head(20))


    Actual  Predicted
0        0          0
1        1          1
2        0          0
3        1          1
4        0          0
5        1          1
6        1          1
7        0          0
8        0          0
9        0          0
10       1          1
11       0          0
12       1          1
13       0          0
14       0          0
15       1          1
16       1          0
17       1          1
18       1          1
19       1          1
